# Generated by Django 4.2.5 on 2023-10-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esmart', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
