# Generated by Django 4.2.5 on 2023-10-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esmart', '0007_react'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='bio_user',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
