# Generated by Django 4.2.5 on 2023-10-27 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esmart', '0013_alter_block_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='group',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='esmart.group'),
        ),
    ]
