# Generated by Django 4.2.5 on 2023-10-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esmart', '0016_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='group',
        ),
    ]
