# Generated by Django 4.2.5 on 2023-10-30 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esmart', '0017_remove_block_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.TextField()),
                ('description', models.TextField()),
                ('page_profile_pic', models.ImageField(blank=True, upload_to='page_profile_pic')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esmart.province')),
            ],
        ),
    ]
