# Generated by Django 4.2.5 on 2023-11-13 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esmart', '0020_page_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='esmart.page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='esmart.province'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='degree',
            field=models.CharField(choices=[('none', 'Không có'), ('high_school', 'THPT'), ('college', 'Cao đẳng'), ('university', 'Đại học')], max_length=50, null=True),
        ),
    ]
