# Generated by Django 4.2.5 on 2023-11-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esmart', '0027_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='img',
            field=models.ImageField(blank=True, upload_to='chats'),
        ),
    ]
